Resources:
  CognitoUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: ${self:custom.stage}-user-pool-client
      GenerateSecret: False
      UserPoolId:
        Ref: CognitoUserPool
Outputs:
  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient
    Export:
      Name: ${self:custom.stage}-CognitoUserPoolClientName