Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-notes
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
Outputs:
  NotesTableArn:
    Value:
      Fn::GetAtt:
        - NotesTable
        - Arn
    Export:
      Name: ${self:custom.stage}-NotesTableArn